config/routes.rb
Rails.application.routes.draw do
    root "pages#home"
    get '/about', to:'pages#about'
    get '/help', to:'pages#help'

    resources :todos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
    validates:name,presence:true
    validates:description,presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def hello
        render plain:"Hello World!"
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home

    end
    def about

    end
    def help
        
    end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    def new
        @todo=Todo.new
    end

    def create
        @todo= Todo.new(todo_params)
        if @todo.save
            flash[:notice]=" Todo was created Successfully!"
            redirect_to todo_path(@todo)
        else
            render 'new'
        end
    end

    def show
        @todo=Todo.find(params[:id])
    end

    def edit
        @todo=Todo.find(params[:id])
    end

    def update
        @todo=Todo.find(params[:id])
        if @todo.update(todo_params)
            flash[:notice]=" Todo was Updated Successfully!"
            redirect_to todo_path(@todo)
        else
            render 'edit'
        end
    end

    def index
        @todo=Todo.all
    end

    def destroy
        @todo=Todo.find(params[:id])
        @todo.destroy
        flash[:notice]=" Todo was Deleted Successfully!"
        redirect_to todos_path
    end


    private
        def todo_params
            params.require(:todo).permit(:name,:description)
        end

        def set_todo
            @todo=Todo.find(params[:id])
        end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg| %>
    <ul>
        <li><%= msg %> </li>
    </ul>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1> This is About Page </h1>

app/views/pages/help.html.erb
<h1> This is help Page </h1>

app/views/pages/home.html.erb
<h1>Hello World ! </h1>

app/views/todos/_forms.html.erb
<% if @todo.errors.any? %>
    <h2> The following errors occured </h2>
    <ul>
        <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for @todo do |f| %>
<p>
    <%= f.label:name %>
    <%= f.text_field:name %>
</p>
<p>
    <%= f.label:description %>
    <%= f.text_area:description %>
</p>
<p>
    <%= f.submit %>
</p>

<% end %>
<p>
    <%= link_to"Back to Todos List" , todos_path %>
</p>

app/views/todos/edit.html.erb
<h1> Edit exixting Todo</h1>
<%= render 'forms' %>

app/views/todos/index.html.erb
<h1> Listing All Todos</h1>
<p>
    <%= link_to"Create a new todo" , new_todo_path %>
</p>
<table>
    <tr>
        <th>Name</th>
        <th>Description</th>
    </tr>
    <% @todo.each do |todo| %>
    <tr>
        <td> <%= todo.name %></td>
        <td><%= todo.description %></td>
        <td><%= link_to"Edit" ,edit_todo_path(todo) %></td>
         <td><%= link_to"Show" ,todo_path(todo) %></td>
         <td><%= link_to"Delete" ,todo_path(todo),method: :delete, data:{confirm:"Are you sure?"} %></td>
    </tr>
    <%end%>
</table>

app/views/todos/new.html.erb
<h1> Create a New Todo  </h1>
<%= render 'forms' %>

app/views/todos/show.html.erb
<h2> Showing Todo</h2>
<p> 
    Name: <%=@todo.name%>
</p>
<p>
    Description: <%=@todo.description%>
</p>
<p>
    <%= link_to"Edit" ,edit_todo_path(@todo) %>
    <%= link_to"Back to Todos List" ,todos_path %>
</p>